# This is a single file for managing both service and deployment 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: server-deployment 
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      component: server 
  template:
    metadata:
      labels: 
        component: server 
    spec: 
      containers:
        - name: server 
          image: ps901/multi-server 
          ports: 
            - containerPort: 5000
---
apiVersion: v1 
kind: Service 
metadata: 
  name: server-client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5 000
      targetPort: 5000    